version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - tbotaq
  allow:
  - dependency-type: direct
  - dependency-type: indirect
