name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: squash and merge
          approve: false
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
