name: Ruby
on: push

env:
  TWITTER_CONSUMER_KEY: twitter_consumer_key
  TWITTER_CONSUMER_SECRET_KEY: twitter_consumer_secret_key
  TWITTER_ACCESS_TOKEN: twitter_access_token
  TWITTER_ACCESS_TOKEN_SECRET: twitter_consumer_secret

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1
        bundler-cache: true
    - name: Ruby version
      run: ruby -v
    - name: Run RSpec
      run: |
        bundle exec rspec --format progress spec/
    - name: Upload codecov report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        directory: ./coverage
